# ===============================
# FONT
# ===============================

font_family JetBrainsMono Nerd Font
bold_font FiraCode Nerd Font
italic_font VictorMono Nerd Font
bold_italic_font VictorMono Nerd Font

font_family_symbols NerdFontsSymbolsOnly
font_family_symbols Noto Color Emoji

font_size 13.0


# ===============================
# CURSOR (ONLY REAL ANIMATION KITTY SUPPORTS)
# ===============================

cursor_shape block
cursor_blink true
cursor_blink_interval 0.5
cursor_trail 200

tab_bar_style powerline
tab_powerline_style round


# ===============================
# TERMINAL DESIGN
# ===============================
window_padding_width 8
hide_window_decorations yes
confirm_os_window_close 0


# ===============================
# TRANSPARENCY
# ===============================
background_opacity 0.85
dynamic_background_opacity yes
background_blur 1


# ===============================
# TMUX INTEGRATION
# ===============================
# Autostart tmux and attach to 'main' session, otherwise create it
shell tmux new-session -A -s main
