# ===============================
# FONT
# ===============================

font_family JetBrainsMono Nerd Font
bold_font FiraCode Nerd Font
italic_font VictorMono Nerd Font
bold_italic_font VictorMono Nerd Font

font_family_symbols NerdFontsSymbolsOnly
font_family_symbols Noto Color Emoji

font_size 12.0


# ===============================
# CURSOR (ONLY REAL ANIMATION KITTY SUPPORTS)
# ===============================

cursor_shape block
cursor_blink true
cursor_blink_interval 0.5
cursor_trail 200

tab_bar_style powerline
tab_powerline_style round


# ===============================
# TERMINAL DESIGN
# ===============================
window_padding_width 8
hide_window_decorations yes
confirm_os_window_close 0


# ===============================
# TRANSPARENCY & COLOR
# ===============================
background #11111b
background_opacity 0.6
dynamic_background_opacity yes
background_blur 2


# ===============================
# SPLITS & WINDOW MANAGEMENT
# ===============================
# Splits layout enable karna
enabled_layouts splits,stack,grid,tall

# Splits create karne ke shortcuts (aur nayi window ko usi directory mein kholna)
map ctrl+shift+v launch --location=vsplit --cwd=current
map ctrl+shift+h launch --location=hsplit --cwd=current

# Splits ke darmiyan navigation (Arrow keys ke zariye)
map ctrl+left neighboring_window left
map ctrl+right neighboring_window right
map ctrl+up neighboring_window up
map ctrl+down neighboring_window down

# Splits ko shift/move karne ke shortcuts
map ctrl+shift+left move_window left
map ctrl+shift+right move_window right
map ctrl+shift+up move_window up
map ctrl+shift+down move_window down


